<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>57c6f513-2c86-4536-95cb-72feeded71e6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Models\OpperSharp.Models.Common\OpperSharp.Models.Common.csproj" />
    <ProjectReference Include="..\Models\OpperSharp.Models.Functions\OpperSharp.Models.Functions.csproj" />
    <ProjectReference Include="..\OpperSharp.Clients\OpperSharp.Clients.csproj" />
    <ProjectReference Include="..\OpperSharp.Utilities\OpperSharp.Utilities.csproj" />
  </ItemGroup>

</Project>
